'''
Specific Exception Handling
It is type of exception handling process.
we can use this only, if we know the type of error.
Syntax
try: 
   programs or problem statement
except errorname:
   solution
'''

# def div():
#     try:
#         a = int(input('Enter the number: '))
#         b = int(input('Enter the number: '))
#         c=a/b
#         print(f'Result is {c}')
#     except ZeroDivisionError:
#         print('Value for b should not be zero')
#         div()
# div()


# def div():
#     try:
#         a = int(input('Enter the number: '))
#         b = int(input('Enter the number: '))
#         c=a/b
#         print(f'Result is {c}')
#     except (ZeroDivisionError,ValueError):
#         print('Value for b should not be zero')
#         print('Value for a and b should be in')
#         div()
# div()



# ---------------------------------------------------------------------------------------------------------- #




'''
Genric Exception Handling
When we dont know the type of error then we should use generic EH.
Generic EH process is capable of handling all the type of error except keyboard interpt.
what is keyboard interpt?
keyboard interpt is a type of error which is generated by user when he/she press ctrl+c or ctrl+z.
With the help this of GEH we can't get solution for particular exception.
Syntax:
try:
    Program or problem statement
except Exception:
    Statement
'''

# def div():
#     try:
#         a = int(input('Enter the number: '))
#         b = int(input('Enter the number: '))
#         c=a/b
#         print(f'Result is {c}')
#     except Exception as e:
#         print(e)
#         div()
# div()


# ---------------------------------------------------------------------------------------------------------- #



'''
Default Exception Handling
To overcome the problem of generic EH we are going to default EH.
It is capable of handling the all type of exception handling including keyboard interupts.
Syntax:
try:
    Program or problem statement
except:
    Statement

'''
def div():
    try:
        a = int(input('Enter the number: '))
        b = int(input('Enter the number: '))
        c=a/b
        print(f'Result is {c}')
        a.append(1)
    except:
        print("Exception is handled please check the inputs")
        div()
div()


# ---------------------------------------------------------------------------------------------------------- #
